#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mem-per-cpu=32G

####################################################################################################
# contact:    wlee9829@gmail.com
# date:       2025_03_28
# script:     mapping_v2.sh
#
# New shell script to simplify the CRSSANT_birch pipeline.
####################################################################################################

####################################################################################################
#  Define the crssant function with preset parameters.
####################################################################################################
function crssant_birch() {

    ## Generate bedgraph for CRSSANT analysis
    echo "Generating bedgraph for CRSSANT..."
    echo
    bedtools genomecov -bg -split -strand + -ibam $Outprefix'_sorted.bam' -g $StaridxPath/chrNameLength.txt > $Outprefix'_plus.bedgraph'
    bedtools genomecov -bg -split -strand - -ibam $Outprefix'_sorted.bam' -g $StaridxPath/chrNameLength.txt > $Outprefix'_minus.bedgraph'

    bgzip *.bedgraph

    tabix -p bed $Outprefix'_plus.bedgraph.gz'
    tabix -p bed $Outprefix'_minus.bedgraph.gz'

    ## CRSSANT analysis
    echo "Starting CRSSANT analysis..."
    echo
    python3 $ScriptPath/crssant_birch.py -o $WorkPath -T $Median $Outprefix'_sorted.bam' $Bed $Outprefix'_plus.bedgraph.gz',$Outprefix'_minus.bedgraph.gz'

    rm *.tbi *.bedgraph.gz
}
####################################################################################################

####################################################################################################
# Specify the following variables with absolute paths for software, Staridx path, Gtf.
####################################################################################################
# ScriptPath:   path to software (e.g., /bin/)
# WorkPath:     path for writing output files  (e.g., /data/mapping/test)
# StaridxPath:  path to genomic index generated by STAR mapping (e.g., /ref/staridx/starhg38mask14add)
# Bed:			path to the genesfile (BED6 format, tab-separated)
# Median:		median segment length determined using the seglen_dist.py script.
# Outprefix:    prefix for output file names, typically the barcode or sample name "R701" (e.g., test)
####################################################################################################
ScriptPath=/project/zhipengl_72/wilsonhl/whl/pipeline/bin/crssant_whl-fork/CRSSANT-master/scripts/
WorkPath=./
StaridxPath=/project/zhipengl_72/labshare/staridx/starhg38mask14add/
Bed=./MALAT1.bed
####################################################################################################
Median=37
Outprefix=DPI-0h_MALAT1
crssant_birch

Median=18
Outprefix=DPI-12h_MALAT1
crssant_birch

Median=30
Outprefix=DPI-2h_MALAT1
crssant_birch

Median=31
Outprefix=DPI-24h_MALAT1
crssant_birch

echo "CRSSANT_birch completed."