#!/bin/bash
#SBATCH --ntasks=2
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=32G

module load gcc/11.3.0
module load openjdk
module load perl/5.36.0

####################################################################################################
# contact:    wlee9829@gmail.com
# date:       2023_03_02
# script:     crssant.sh
#
# This script standardizes the mapping of pre-processed data from PARIS- and SHARC-based sequencing.
# STAR and various scripts from the CRSSANT pipeline are used. Change paths and variables accordingly.
#
# STAR: https://github.com/alexdobin/STAR
# CRSSANT: https://github.com/zhipenglu/CRSSANT/tree/master/scripts
####################################################################################################

####################################################################################################
# Specify the following variables with absolute paths for software, working path, fastq/gtf.
####################################################################################################
# ScriptPath:   path to software (e.g., /bin/)
# WorkPath:     path for writing output files  (e.g., /data/mapping/test)
# StaridxPath:  path to genomic index generated by STAR mapping (e.g., /ref/staridx/starhg38mask14add)
# Bed:          path to bed file containing genes (e.g., /ref/bed)
# Outprefix:    prefix for output file names, typically the barcode or sample name "R701" (e.g., test)
####################################################################################################
ScriptPath=/crssant/CRSSANT-master/scripts
WorkPath=/data/crssant
StaridxPath=/staridx/starhg38mask14add
Bed=/hs45S_genes.bed
Outprefix=0h
####################################################################################################

####################################################################################################
#  Define the crssant function with preset parameters.
####################################################################################################
function crssant() {

	## Merge the gap1_filtered and trans/rri.sam files to crssant.sam
	python3 $ScriptPath/merger.py $Outprefix'_prigap1_filtered.sam' $Outprefix'_pritrans.sam' $Outprefix'_pri_crssant.sam'
	echo "SAM files combined..."
	echo
	## Generate a sorted.bam for IGV
	echo "Converting to sorted BAM for IGV..."	
	samtools view -bS -o $Outprefix'_pri_crssant.bam' $Outprefix'_pri_crssant.sam'
	samtools sort -o $Outprefix'_pri_crssant_sorted.bam' $Outprefix'_pri_crssant.bam'
	samtools index $Outprefix'_pri_crssant_sorted.bam'

	## Generate bedgraph for CRSSANT analysis
	echo "Generating bedgraph for CRSSANT..."
	echo
	bedtools genomecov -bg -split -strand + -ibam $Outprefix'_pri_crssant_sorted.bam' -g $StaridxPath/chrNameLength.txt > $Outprefix'_plus.bedgraph'
	bedtools genomecov -bg -split -strand - -ibam $Outprefix'_pri_crssant_sorted.bam' -g $StaridxPath/chrNameLength.txt > $Outprefix'_minus.bedgraph'

	## CRSSANT analysis
	echo "Starting CRSSANT analysis..."
	echo
	python3 $ScriptPath/crssant.py -cluster cliques -t_o 0.2 -out ./ $Outprefix'_pri_crssant.sam' $Bed $Outprefix'_plus.bedgraph',$Outprefix'_minus.bedgraph'
	##mkdir $WorkPath/$Outprefix & mv *_crssant* $WorkPath/$Outprefix && mv *.bedgraph $WorkPath/$Outprefix
}
####################################################################################################
crssant
echo "CRSSANT completed, see $Outprefix'_pri_crssant.cliques.t_o0.2.sam'"
echo
####################################################################################################